---
output: html_document
runtime: shiny
---

<style type="text/css">
.main-container {
max-width: 1800px;
margin-left: auto;
margin-right: auto;
}
</style>

```{r global, include=FALSE}

# load required packages
library(esquisse)
library(readxl)
library(shiny)
library(tidyverse) # always last to avoid conflicts

# prevent r errors etc. appearing to user
knitr::opts_chunk$set(echo = FALSE)

dat_raw <- read_excel("data/processed/BIOL2015-M2-2024_plot-level.xlsx",
                      sheet = "plot-level")

# no longer cleaning data at runtime, so nothing req'd here
dat <- dat_raw 

```

# Module 2 --- soil, vegetation and spiders
### BIOL2015 Field Ecology
###### v2.2 | 28/06/2024 | jwh  

```{r esquisse, echo=FALSE}

renderUI(
  esquisse_ui(id = "main")
)

esq_rv <- esquisse_server(id = "main",
                          data_rv = dat,
                          name = "dat")
# reactive value output claims to have three slots for code_filter, code_plot
# and data, but the data slot has always been empty in testing -- therefore
# no summary dataset shown below esquisse UI in this version

```

```{r exit-and-scratch, echo=FALSE}

knitr::knit_exit()

```


